### ISSUE TITLE
After installing and restarting Anki, plug-in crashes

### ISSUE THREAD

**Issue by sj4nes** [luoliyan/incremental-reading#106]
**Expected behavior**

I don't know, I've never seen this plug-in work.

**Crash Trace**

```
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 8.1
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-18 00:16:59

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\main.py", line 155, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 192, in setupProfile
  File "aqt\main.py", line 365, in loadProfile
  File "aqt\gui_hooks.py", line 648, in __call__
  File "lib\site-packages\anki\hooks.py", line 475, in runHook
  File "C:\Users\simon_000\AppData\Roaming\Anki2\addons21\935264945\main.py", line 53, in onProfileLoaded
    self.settings = SettingsManager()
  File "C:\Users\simon_000\AppData\Roaming\Anki2\addons21\935264945\settings.py", line 98, in __init__
    self.load()
  File "C:\Users\simon_000\AppData\Roaming\Anki2\addons21\935264945\settings.py", line 114, in load
    self._loadExisting()
  File "C:\Users\simon_000\AppData\Roaming\Anki2\addons21\935264945\settings.py", line 123, in _loadExisting
    self.settings = json.load(jsonFile)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by AlexRiina** [comment]
This plugin maintains its configuration in a .json file and it looks like it is unable to read yours for some reason. If you've never used the plugin before, you can probably delete the `_ir.json` file in your collection.media. If you've done any configuration it may be best to try to repair the json by editing the file
