### ISSUE TITLE
Caught exception: Traceback (most recent call last):

### ISSUE THREAD

**Issue by kunpeng9** [luoliyan/incremental-reading#115]
**Describe the bug**
似乎和review_heatmap冲突了；It seems and review_ Heatmap addon conflicts;
**To Reproduce**

**Expected behavior**
修复冲突或问题
**Screenshots**

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]
 - Anki Version [e.g. v2.0.52, v2.1.5]
- Incremental Reading Version [e.g. v0.5.3-beta]
windows anki版本 2.1.35 (84dcaa86)Incremental Reading Version v4103
**Additional context**
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-15 18:05:02

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<D:\files knowledge\anki\decorator.pyc:decorator-gen-76>", line 2, in _linkHandler
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\review_heatmap\links.py", line 74, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "aqt\overview.py", line 67, in _linkHandler
  File "aqt\main.py", line 661, in moveToState
  File "aqt\main.py", line 683, in _reviewState
  File "<D:\files knowledge\anki\decorator.pyc:decorator-gen-48>", line 2, in show
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 629, in repl
  File "aqt\reviewer.py", line 65, in show
  File "<D:\files knowledge\anki\decorator.pyc:decorator-gen-40>", line 2, in nextCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 633, in repl
  File "aqt\reviewer.py", line 118, in nextCard
  File "aqt\reviewer.py", line 196, in _showQuestion
  File "aqt\gui_hooks.py", line 795, in __call__
  File "anki\hooks.py", line 594, in runFilter
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 38, in prepareCard
    if (isIrCard(card) and self.settings['limitWidth']) or self.settings[
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

**Comment by kunpeng9** [comment]
另外一个报错是Another mistake is
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-15 18:05:02

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

**Comment by kunpeng9** [comment]
另外一个报错是Another mistake is
错误  
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-15 18:05:02

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\view.py", line 117, in saveScroll
    if viewingIrText():
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 35, in viewingIrText
    isIrCard(mw.reviewer.card)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\935264945\util.py", line 29, in isIrCard
    card.model()['name'] == mw.readingManager.settings['modelName']
AttributeError: 'ReadingManager' object has no attribute 'settings'
