### ISSUE TITLE
'Show Answer' causes error

### ISSUE THREAD

**Issue by lukenormile** [luoliyan/incremental-reading#119]
**Describe the bug**
When I press 'Show Answer' on an imported or extracted card, Anki shows an error and no scheduling choices are displayed. 

**To Reproduce**
1. Import a webpage using alt+3
2. Go into review mode on my Imports Deck
3. Optionally make highlights, extractions etc. This seems to succeed.
4. Click on 'Show Answer' - the card now says "When do you want to see this card again?", but the 'Show Error' dialogue is not replaced with interval buttons, and Anki displays a pop up stating that an error occurred (debug info pasted below).

The same behavior occurs when reviewing a card that I extracted from the original import.

**Expected behavior**
I expect the 'Show Answer' button to be replaced with other buttons with options for when I will see the card again.

**Screenshots**
<img width="862" alt="image" src="https://user-images.githubusercontent.com/3102932/129227892-e96a1377-ac9e-49eb-abed-7c28d994f247.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/3102932/129227980-c142a7b1-80a3-4cc9-849f-b17480ffd3e7.png">

**Specs (please complete the following information):**
 - OS: Mac 10.15.7
 - Anki Version 2.1.46 (94913ec2)
 - Incremental Reading Version 4.10.3

**Debug info printed by Anki error pop-up**
  Debug info:
  Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
  Platform: Mac 10.15.7
  Flags: frz=True ao=True sv=2
  Add-ons, last update check: 2021-08-11 20:30:31
  
  Caught exception:
  Traceback (most recent call last):
    File "aqt/webview.py", line 538, in handler
    File "aqt/reviewer.py", line 705, in _onTypedAnswer
    File "aqt/reviewer.py", line 386, in _showAnswer
    File "aqt/reviewer.py", line 760, in _showEaseButtons
    File "aqt/reviewer.py", line 847, in _answerButtons
    File "aqt/reviewer.py", line 833, in but
    File "decorator.py", line 232, in fun
    File "anki/hooks.py", line 89, in decorator_wrapper
    File "anki/hooks.py", line 86, in repl
  TypeError: buttonTime() got multiple values for argument '_old'

**Comment by lukenormile** [comment]
**Update**
I ascertained that this behavior occurs in *all* cards and decks, including ones I created before installing IR.

**Comment by TheBlackBeans** [comment]
I have the same behavior. I have tried on a complete new profile, on which I have never used the add-on (besides installing it), and it still breaks.

**Comment by GeoBobCa** [comment]
I have had the same problem.   The description provided by lukenormile accurately describes what's happening on my machine. I have only one other add-on installed.

Here's the error message I received:

Debug info:
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-22 09:02:16

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 538, in handler
  File "aqt\reviewer.py", line 705, in _onTypedAnswer
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\Bob\AppData\Roaming\Anki2\addons21\1374772155\main.py", line 233, in onShowAnswer
    return _old(self)
  File "aqt\reviewer.py", line 386, in _showAnswer
  File "aqt\reviewer.py", line 760, in _showEaseButtons
  File "aqt\reviewer.py", line 847, in _answerButtons
  File "aqt\reviewer.py", line 833, in but
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
TypeError: buttonTime() got multiple values for argument '_old'

**Comment by chromial** [comment]
this error is still present in version 2.1.49
---------------------------------------------------------------------
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-11 10:34:07

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "aqt\reviewer.py", line 704, in _onTypedAnswer
  File "aqt\reviewer.py", line 383, in _showAnswer
  File "aqt\reviewer.py", line 759, in _showEaseButtons
  File "aqt\reviewer.py", line 846, in _answerButtons
  File "aqt\reviewer.py", line 832, in but
  File "decorator.py", line 232, in fun
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
TypeError: buttonTime() got multiple values for argument '_old'

**Comment by tvhong** [comment]
Hi,
This error should be fixed in https://github.com/luoliyan/incremental-reading/commit/4be88a5ad116ca9ce412f7989013167f7448db6c .

A new release of the IR add-on will address this issue.
