### ISSUE TITLE
Plugin crashes on OSX during on boot-- fresh install

### ISSUE THREAD

**Issue by heymatthew** [luoliyan/incremental-reading#131]
**Describe the bug**
Installing the 'incremental reading' plugin on OSX Ventura (﻿﻿﻿﻿13.2), Anki reports plugin crashes on startup.

**To Reproduce**
1. Install a fresh code of Anki on OSX Ventura
2. navigate to Tools → Add-ons → Get Add-ons...
3. enter the code 935264945 (from [Plugin Page](https://ankiweb.net/shared/info/935264945))
5. restart anki
6. boom

```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Incremental Reading v4103⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/me/Library/Application Support/Anki2/addons21/935264945/__init__.py", line 17, in <module>
    from .main import ReadingManager
  File "/Users/me/Library/Application Support/Anki2/addons21/935264945/main.py", line 28, in <module>
    from .importer import Importer
  File "/Users/me/Library/Application Support/Anki2/addons21/935264945/importer.py", line 48, in <module>
    from .lib.feedparser import parse
  File "/Users/me/Library/Application Support/Anki2/addons21/935264945/lib/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
⁩```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Specs (please complete the following information):**
 - OS: OSX Ventura (﻿﻿﻿﻿13.2),
 - Anki Version: ⁨2.1.57 (6b7d372c)⁩, Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
- Incremental Reading Version v4103

**Additional context**
Add any other context about the problem here.

**Comment by tvhong** [comment]
Hi there,
This plugin hasn't been working for a while, try the unofficial clone for now: https://ankiweb.net/shared/info/999215520 (disclaimer: I'm the author of the unofficial clone and a contributor to this repo. Unfortunately, don't have permissions to update the Addon on Anki).
